services:
  bot:
    build:
      dockerfile: Dockerfile
      context: ./bot
    env_file:
      - .env
    restart: on-failure:3
    volumes:
      - bot-logs:/app/logs
    develop:
      watch:
        - action: sync+restart
          path: ./bot
          target: /app
          ignore:
            - .venv/
            - logs/
        - action: rebuild
          path: ./pyproject.toml

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    env_file:
      - .env
    ports:
      - 8000:8000
    restart: on-failure:3
    volumes:
      - api-logs:/app/logs
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /app
          ignore:
            - .venv/
            - logs/
        - action: rebuild
          path: ./pyproject.toml

volumes:
  bot-logs: {}
  api-logs: {}
